### ISSUE TITLE
あるページで一度hueの接続に成功しても、違うページではまた「Please press link button on the bridge」と言われてしまう。

### ISSUE THREAD

**Issue by shumpei** [HTML5ExpertsHackathon/hue-video-ambilight#1]
一度hueの接続に成功したら、その設定情報を使いまわして欲しい。
contentscriptが動作しているオリジンのlocalStorageを使用しているため、オリジンが違うページに行くと設定情報がクリアされるという状態か？

代わりに、chrome.storageを使うようにしてもいいかも。

**Comment by kyo-ago** [comment]
修正しましたー

**Comment by shumpei** [comment]
ちょっと試してみたのですが、直ってない？(^^;

これまで「Connect to hue」を試していないページ（例えば↓）とかで試してみると、「Please press link button on the bridge」が出てしまいます。
http://www.html5rocks.com/ja/tutorials/video/basics/

また、リンクボタンを押すと「Connected」にはなりますが、その状態でビデオを再生しても動きません。ページをリロードして、再度「Connect to hue」を押すと、「Ready to play」になり、その状態でやっと動作するようになります。

**Comment by kyo-ago** [comment]
こちらでは上記ページ（今回はじめて見た）で正しく動作できました。
（「Connect to hue」を押せばすぐに「Ready to play」になった）

上記動作が一つ前のバージョンの動作と同じように見えるので、 chrome://extensions/ から「Reload (⌘R)」を行ってみてもらえないでしょうか？

**Comment by shumpei** [comment]
あれ、本当だ。
おかしいな、リロードしたつもりだったのですが・・・（汗）
無駄に時間取らせちゃってすいません！！！
クローズします。
