### ISSUE TITLE
色の解析ロジックが遅い

### ISSUE THREAD

**Issue by shumpei** [HTML5ExpertsHackathon/hue-video-ambilight#3]
解析元のvideoやimgが大きいと、処理が全然終わらない。
パフォーマンスチューニングが必要。

**Comment by shumpei** [comment]
着手します。

**Comment by shumpei** [comment]
関数のインライン化などで、以前より2倍くらいは速くなった。
しかし、ビデオのサイズに応じて線形で処理時間が増えていくのをどうにかしたい。

**Comment by shumpei** [comment]
640x360とかでは、まあ実用的な速度が出るので、一旦クローズします。
それ以上の速度が欲しくなった場合はReopenします。

**Comment by kyo-ago** [comment]
一応transferable objects使うと結構簡単にデータの転送速度部分を高速化できるかもしれません。
（転送速度部分がどの程度時間を食ってるか不明なので一旦メモだけにします）
https://developer.mozilla.org/ja/docs/Web/Guide/Performance/Using_web_workers#Passing_data_by_transferring_ownership_(transferable_objects)
http://lab.sonicmoov.com/development/web-workers-with-transferable-objects/

**Comment by shumpei** [comment]
Transferable Objectを使うように変更しました。

**Comment by shumpei** [comment]
あと、手っ取り早くパフォーマンスを改善する策を思いつきました。
色の解析ロジックに渡す前に、canvasを小さくリサイズしてしまえばOKですね。

**Comment by kyo-ago** [comment]
:+1:
