### ISSUE TITLE
「connect to hue」ボタンのUIをカッコよく

### ISSUE THREAD

**Issue by shumpei** [HTML5ExpertsHackathon/hue-video-ambilight#4]
ここがカッコいいと、印象がぐっと良くなりそう。

**Comment by kyo-ago** [comment]
現状、youtubeがcssでかなりキツイresetを行ってるので無理やり対応してました。
iframeで外部cssに影響されないようにしてデザインを独自化させようと思います。

**Comment by kyo-ago** [comment]
一旦iframe化して、埋め込んでいたcssのresetを削除しました。
デザイン的なところは難しいので一旦終了させてください。
（ボタンを画像化するとかは簡単ですが、「ぱっと見これ用の画像とわかるか」、「押しやすい感じがするか」、「多言語化どうする」とか考えると答えが出ない。。。）
