### ISSUE TITLE
再生中videoの画像とhueの色が一致しない

### ISSUE THREAD

**Issue by kyo-ago** [HTML5ExpertsHackathon/hue-video-ambilight#7]
環境依存の可能性もあり
以下のビデオで検証
http://www.youtube.com/watch?v=ScVAUJ3_UPY

**Comment by shumpei** [comment]
こちらでも、同様の感覚です。
アルゴリズムを見なおしてみます。

ただ、以前もこのアルゴリズムは使用していたのですが、その時はアルゴリズムによる解析と、人間が見た感覚の差という結論で終えちゃいました。

**Comment by shumpei** [comment]
こちら、色解析のアルゴリズムに問題はなく、RGB->HSL変換と、hueにその値を送る際の処理に問題がありました。
修正したのですが、まだ少し違和感があります（ただ、前よりはずいぶん良くなりました）。
時間がないので、とりあえずpushしました。引き続き対応を進めたいと思います。

**Comment by kyo-ago** [comment]
よく使われている色の上位3色を混ぜたらいい感じになったので終了したいと思います。
