### ISSUE TITLE
widthやheightが指定されていないvideoを処理しようとするとエラー？

### ISSUE THREAD

**Issue by shumpei** [HTML5ExpertsHackathon/hue-video-ambilight#8]
http://www.w3.org/2010/05/video/mediaevents.html

で試したところ、index.js:221でエラー。
source.videoWidth/videoHeight/width/heightすべて0という値でした。

**Comment by kyo-ago** [comment]
対応しました。
ただ、上記のページのvideoは外部originに存在するため対応できません（ #6 で対応します）
